name: Update Swagger Docs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  job1:
    name: Update Swagger Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.2

      - name: Get latest swagger JSON and update it for prod display.
        run: |
          curl https://stagingapi.smokeball.com/swagger/docs/swagger.json > ./reference/swagger.json
          sed -i 's/stagingapi.smokeball.com/api.smokeball.com/g' ./reference/swagger.json
          sed -i 's/Staging API/API/g' ./reference/swagger.json ./reference/swagger.json

      - name: actionsx/prettier
        uses: actionsx/prettier@v2
        with:
          args: --write ./reference/swagger.json

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Update Swagger Docs"
          git push
